import { url } from 'inspector';
import '../app/globals.css';
import { Inter } from 'next/font/google';
import Aside from '@/components/Aside';
import { useMemo, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showAside, setShowAside] = useState(true);
  const AsideComponent = useMemo(() => {
    return showAside ? (
      <Aside></Aside>
    ) : (
      <></>
    );  
  }, [showAside]);

  const Onclick = () => {
    setShowAside(!showAside);
  };
  return (
    <>
      <div
        className="flex items-center justify-between"
        style={{
          background: '#08B2FF',
          width: '100%',
          minHeight: '3rem',
        }}
      >
        <button
          data-drawer-toggle="sidebar-multi-level-sidebar"
          className="m-4"
          onClick={Onclick}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            style={{
              width: '2rem',
              height: '2rem',
            }}
            viewBox="0 0 16 16"
          >
            <path
              fillRule="evenodd"
              d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
            />
          </svg>
        </button>
        <h1
          style={{
            fontSize: '1.5rem',
            color: '#FFFFFF',
            textShadow: '10px 10px 10px rgba(0, 0, 0, 0.25)',
          }}
        >
          VISUALCOM
        </h1>
        <button className="m-4">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            style={{ width: '1.5rem', height: '1.5rem' }}
            viewBox="0 0 16 16"
          >
            <path
              fillRule="evenodd"
              d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z"
            />
          </svg>
        </button>
      </div>
      {AsideComponent}
      {children}
    </>
  );
}
